---
# TODO add a unique name to the action.
# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#name
name: Some name
# TODO add a description to the action.
# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#description
description: Some description
# TODO add an author to the action.
# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#author
author: Some author
# TODO set an icon for the action.
# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#branding
branding:
  icon: play-circle
  color: blue
# TODO add a mapping of inputs for the action.
# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#inputs
inputs: {}
# TODO add a mapping of outputs for the action.
# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#outputs-for-composite-actions
outputs: {}
runs:
  using: composite
  # TODO add steps describing what the action should do.
  # https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#runssteps
  steps:
    - name:
      shell: bash
      run: echo TODO add steps
